# dev(192.168.30.1)(路由器):
# dhcp: 192.168.2.246
# d05(DUT): 192.168.3.169
# d03(DUT): 192.168.2.210
# d03(DUT): 192.168.1.214
# export CI_ENV=dev

# 和108相连,lan口已满

# 当前只有dhcp服务
dhcp:
  type: D03
  bmc: 192.168.2.246
  ip: 192.168.30.2
  mac: c0:a8:02:f6:00:04
  filename: open-estuary
  next-server: 192.168.30.101
  open-estuary: "estuary_install/grubaa64.efi"
  sailing: "sailing_install/grubaa64.efi"
  linaro: "./linaro_install/grubaa64.efi"

# 主力d05开发机器
d05ssh01:
  type: D05
  bmc: 192.168.3.169
  ip: 192.168.30.201
  mac: c0:a8:02:a9:00:04
  filename: open-estuary
  next-server: 192.168.30.101
  open-estuary: "estuary_install/grubaa64.efi"
  sailing: "sailing_install/grubaa64.efi"
  linaro: "./linaro_install/grubaa64.efi"


# 主力 d03 开发机器
d03ssh01:
  type: D03
  bmc: 192.168.2.210
  ip: 192.168.30.202
  mac: c0:a8:02:d2:00:04
  filename: open-estuary
  next-server: 192.168.30.101
  open-estuary: "estuary_install/grubaa64.efi"
  sailing: "sailing_install/grubaa64.efi"
  linaro: "./linaro_install/grubaa64.efi"


# 李涛使用
#  - d03ssh02:
#      type: D03
#      bmc: 192.168.1.214
#      ip: 192.168.30.204
